### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by ghost** [dodoflix/minecraft-stress-tester#1]
matip@DESKTOP-K4J0V5L:~/minecraft-stress-tester/src$ npm install
npm WARN Invalid version: "0.5"
npm WARN src No description
npm WARN src No repository field.
npm WARN src No README data
npm WARN src No license field.

up to date in 0.308s
found 0 vulnerabilities

**Comment by dodoflix** [comment]
Sorry for late I didn't saw the issue. It look's like your npm Is the problem I tried and everything worked perfect. Try to delete your current npm and install the latest lts package.
